# EastWhitelist by EastRane

# Language for the plugin.
# Available options: ru_RU
language: ru_RU

# If true, players who are not on the whitelist will not be able to join the server
enabled: true

# Available options: yaml, mysql
storage: yaml

mysql:
  # Database server address
  host: 'localhost'
  # Database server port
  port: '3306'
  # Name of the database to use
  database: 'database'
  # Database user
  username: 'root'
  # Database password
  password: 'password'
  # Name of table in database
  table: 'ew_hub'
  # If true, the server will immediately shut down on any SQL exception
  shutdown_on_exception: false

debug:
  # If true, debug messages will be logged to the console
  console: true
  # If true, debug messages will be written to the debug.yml file
  file: false